package captainhaddock

import (
	"bytes"
	"math/rand"
)

var insults = [...]string{
	"accapareur",
	"aérolithe",
	"amiral de bateau-lavoir",
	"amphitryon",
	"anacoluthe",
	"analphabète",
	"analphabète diplômé",
	"animal",
	"antropophage",
	"anthropopithèque",
	"apache",
	"apprenti-dictateur à la noix de coco",
	"apophtegme",
	"arlequin",
	"ascenseur",
	"astronaute d’eau douce",
	"athlète complet",
	"autocrate",
	"autodidacte",
	"babouin",
	"bachi-bouzouk",
	"bachi-bouzouk de tonnerre de Brest",
	"bachi-bouzouk des Carpathes",
	"bandit",
	"bayadère de carnaval",
	"bibelot",
	"bibendum",
	"bidule",
	"boit-sans-soif",
	"bombe atomique",
	"bougre d’ectoplasme à roulettes",
	"bougre d’ectoplasme de moule à gaufres",
	"bougre d’amiral de bateau-lavoir",
	"bougre de crème d’emplâtre à la graisse de hérisson",
	"bougre d’extrait de cornichon",
	"bougre d’extrait de crétin des Alpes",
	"bougre d’extrait d’hydrocarbure",
	"bougre de faux jeton à la sauce tartare",
	"bougre de méchant Blanc",
	"bougre de mouchard",
	"bougre d’olibrius",
	"bougre d’ostrogoth",
	"bougre de papou des Carpathes",
	"bouge de petit cornichon",
	"bougre de phénomène de tonnerre de Brest",
	"bougre de phénomène de moule à gaufres de tonnerre de Brest",
	"bougre de sauvage d’aérolithe de tonnerre de Brest",
	"bougre de zouave",
	"brigand",
	"brontosaure",
	"brute",
	"bulldozer à réaction",
	"cachalot",
	"cake-walk",
	"canaille",
	"Canaque",
	"cannibale",
	"cannibale emplumé",
	"capitaine de bateau-lavoir",
	"casse-pieds",
	"catachrèse",
	"cataplasme",
	"cercopithèque",
	"cercueil volant",
	"chauffard",
	"chenapan",
	"choléra",
	"chouette mal empaillée",
	"chrysanthème",
	"cigare volant",
	"cloche à fromage",
	"cloporte",
	"clown",
	"clysopompe",
	"coléoptère",
	"coloquinte",
	"coloquinte à la graisse de hérisson",
	"concentré de moule à gaufres",
	"coquin",
	"cornemuse",
	"cornichon",
	"cornichon de zouave de tonnerre de Brest",
	"cornichon diplômé",
	"corsaire",
	"coupe-jarret",
	"cow-boy de la route",
	"crème d’emplâtre à la graisse de hérisson",
	"crétin de l’Himalaya",
	"crétin des Alpes",
	"crétin des Balkans",
	"cromagnon",
	"cuistre",
	"cyanure",
	"cyclone",
	"cyclone ambulant",
	"cyclotron",
	"Cyrano à quatre pattes",
	"diable",
	"diable de zouave",
	"diablesse",
	"diplodocus",
	"doryphore",
	"dynamiteur",
	"écornifleur",
	"écraseur",
	"ectoplasme",
	"ectoplasme à roulettes",
	"égoïste",
	"emplâtre",
	"emplâtré à la graisse de hérisson",
	"empoisonneur",
	"encordé",
	"énergumène",
	"enfonceur de porte ouverte",
	"enragé",
	"épouvantail",
	"équilibriste",
	"esclavagiste",
	"escogriffe",
	"escroc",
	"espèce de loup-garou à la graisse de renoncule de mille sabords",
	"espèce de porc-épic mal embouché",
	"entêté",
	"extrait d’emplâtre",
	"extrait d’hydrocarbure",
	"extrait de cornichon",
	"face de brute",
	"farceur",
	"faux frère",
	"faux jeton",
	"faux jeton à la sauce tartare",
	"fieffé menteur",
	"flibustier",
	"flibustier de carnaval",
	"flûte",
	"forban",
	"fourbe",
	"froussard",
	"galopin",
	"gamin",
	"gangster",
	"garde-côtes à la mie de pain",
	"gargarisme",
	"garnement",
	"gibier de potence",
	"goujat",
	"graine de vaurien",
	"grand escogriffe",
	"grand lâche",
	"gredin",
	"grenouille",
	"gros-plein-de-soupe",
	"grotesque polichinelle",
	"gyroscope",
	"hérétique",
	"hors-la-loi",
	"hurluberlu",
	"hydrocarbure",
	"iconoclaste",
	"Inca de carnaval",
	"individou de général de tonnerre de Brest",
	"invertébré",
	"isotope",
	"ivrogne",
	"jet d’eau ambulant",
	"jeune chenapan",
	"jeune impertinent",
	"jocrisse",
	"judas",
	"jus de réglisse",
	"Khroumir",
	"Ku Klux Klan",
	"Kanak",
	"lâche",
	"lascar",
	"lépidoptère",
	"logarithme",
	"loup-garou à la graisse de renoncule de mille tonnerres de Brest",
	"macaque",
	"macrocéphale",
	"malappris",
	"malheureux",
	"malheureuse",
	"malotru",
	"mamelouk",
	"maraud",
	"marchand de guano",
	"marchand de tapis",
	"marin d’eau douce",
	"marmotte mal révéillée",
	"mégacycle",
	"mégalomane",
	"mercanti",
	"mercenaire",
	"mérinos",
	"mérinos mal peigné",
	"migou de malheur",
	"misérable",
	"misérable ectoplasme",
	"misérable ver de terre",
	"mitrailleur à bavette",
	"moricaud",
	"mouchard",
	"moujik",
	"moule à gaufres",
	"moussaillon de malheur",
	"moussaillon du diable",
	"mufle",
	"Mussolini de carnaval",
	"naufrageur",
	"négrier",
	"noix de coco",
	"nyctalope",
	"olibrius",
	"ophicléide",
	"ornithorynque",
	"oryctérope",
	"Ostrogoth",
	"ours mal léché",
	"paltoquet",
	"pantoufle",
	"Papou",
	"Papou des Carpathes",
	"paranoïaque",
	"Patagon",
	"Patagon de Zoulou",
	"patapouf",
	"patate",
	"pauvre bougre",
	"pauvre type",
	"Peau-rouge",
	"père volant",
	"péronnelle",
	"perruche bavarde",
	"perroquet bavard",
	"perroquet déplumé",
	"petit choléra",
	"petit ornithorynque",
	"petite tigresse",
	"petit vaurien",
	"phénomène",
	"phlébotome",
	"phylactère",
	"phylloxéra",
	"pignouf",
	"pirate",
	"pirate d’eau douce",
	"pirate du ciel",
	"pleurnichard",
	"polichinelle",
	"polygraphe",
	"porc-épic mal embouché",
	"potentat",
	"profiteur",
	"projectile guidé",
	"protozoaire",
	"pyromane",
	"rapace",
	"rat",
	"ravachol",
	"renégat",
	"rhizopode",
	"rocaille de tonnerre de Brest",
	"rocambole",
	"sacré mitrailleur à bavette",
	"sacripant",
	"sajou",
	"sale bête",
	"saleté d’appareil à sous",
	"sale vilaine bête de tonnerre de Brest",
	"saltimbanque",
	"sapajou",
	"satrape",
	"sauvage",
	"sauvage d’aérolithe",
	"scaphandrier d’eau de vaisselle",
	"scélérat",
	"schizophrène",
	"scolopendre",
	"scorpion",
	"serpent",
	"simili-Martien à la graisse de cabestan",
	"sinapisme",
	"sinistre farceur",
	"sombre brute",
	"sombre oryctérope",
	"soulographe",
	"sous-produit d’ectoplasme",
	"squelette de pantoufle",
	"squelette désossé",
	"tchouk-tchouk-nougat",
	"technocrate",
	"tête de lard",
	"tête de mule",
	"tigresse",
	"topinambour",
	"tortionnaire",
	"trafiquant de chair humaine",
	"traîne-potence",
	"traître",
	"tricheur",
	"troglodyte",
	"trompe-la-mort",
	"troufignol",
	"vampire",
	"vandale",
	"va-nu-pieds",
	"vaurien",
	"végétarien",
	"ver de terre",
	"Vercingétorix de carnaval",
	"vermine",
	"vieille baderne",
	"vieille branche",
	"vieille coque rouillée",
	"vieille marmotte",
	"vieille perruche bavarde",
	"vieux cachalot",
	"vieux cornichon",
	"vipère",
	"vivisectionniste",
	"volatile de malheur",
	"voleur",
	"voleur d’enfants",
	"zèbre",
	"zigomar",
	"zouave",
	"zouave interplanétaire",
	"Zoulou",
	"Aztèques",
	"bande de jeunes effrontés",
	"bande de joyeux drilles",
	"bande d’ectoplasmes de tonnerre de Brest",
	"bande d’emplâtres",
	"bande d’enragés",
	"bande d’escrocs",
	"bande d’hurluberlus",
	"bande de bachi-bouzouks",
	"bande de brutes",
	"bande de Canaques",
	"bande de Ku Klux Klans",
	"bande de pirates",
	"bande de voleurs",
	"bande de Zapotèques de tonnerre de Brest",
	"bon sang",
	"le diable vous emporte",
	"que le diable vous étripatouille",
	"enfer et damnation",
	"KRRTCHMVRTZ",
	"mille milliards de mille millions de mille sabords",
	"mille milliards de mille sabords",
	"mille milliards de mille sabords de tonnerre de Brest",
	"mille milliards de tonnerres de Brest",
	"mille millions de mille milliards de mille sabords",
	"mille millions de mille milliards de mille sabords de tonnerre de Brest",
	"mille millions de mille sabords",
	"mille millions de mille sabords de tonnerre de Brest",
	"mille millions de sabords",
	"mille millions de tonnerres de Brest",
	"mille sabords",
	"mille tonnerres",
	"mille tonnerres de Brest",
	"morues dans un carton à chapeau",
	"MRKRPXZKRMTFRZ",
	"nom d’une pipe",
	"parasites",
	"pyrophores",
	"squatters",
	"tas de sauvages",
	"tonnerre",
	"tonnerre de Brest",
	"tonnerre de tonnerre de Brest",
	"vermicelles",
	"Wisigoths",
	"Zapotèques",
}

func HaddockSays() string {
	var s string
	buff := bytes.NewBufferString(s)

	for i := 0; i < rand.Intn(3)+2; i++ {
		if i != 0 {
			buff.WriteByte(' ')
		}
		buff.WriteString(insults[rand.Intn(len(insults))])
		buff.WriteString("!!")
	}
	return buff.String()
}
